name: 'sn-create-change-req'
description: 'Creates a change request record on ServiceNow.'
author: 'dannevesdantas'
branding:
  color: green
  icon: user-check
inputs:
  instance-url:
    description: 'ServiceNow instance URL'
    required: true
outputs:
  chg-number:
    description: 'The change request number'
  sys_id:
    description: 'Change request Unique record identifier'
runs:
  using: 'node12'
  main: 'index.js'