name: 'sn-create-change-req'
description: 'Creates a change request record on ServiceNow.'
author: 'dannevesdantas'
branding:
  color: green
  icon: user-check
inputs:
  who-to-greet:  # id da entrada
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id da saída
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'